#!/usr/bin/env python3
"""Validate the structure of a voice skill generated by voice-cloner.

The validator cannot judge whether a captured voice sounds authentic; only the
voice owner can do that. It checks the file structure and detects common AI
writing patterns that may have leaked into the generated document.

Usage:
    python3 scripts/validate_skill.py path/to/SKILL.md
"""

import re
import sys


REQUIRED_SECTIONS = [
    "When to use",
    "Absolute rules",
    "Vocabulary",
    "Syntax and rhythm",
    "Tone by register",
    "Speech mode and writing mode",
    "Calibrated examples",
    "Self-validation checklist",
    "Known limitations",
]

# These phrases rarely belong to a real human voice unless samples support them.
ANTI_PATTERNS = [
    "i hope this helps",
    "please let me know if you have any questions",
    "great question",
    "excellent question",
    "let's dive in",
    "let's explore together",
    "in today's world",
    "in the modern world",
    "it's not just",
    "it is not just",
]

PLACEHOLDERS = [
    "NAME",
    "CONTEXT",
    "Generic text here",
    "Real voice text here",
]


def read_file(path):
    with open(path, "r", encoding="utf-8") as file:
        return file.read()


def validate_frontmatter(text, errors, warnings):
    if not text.startswith("---\n"):
        errors.append("The file does not start with YAML frontmatter on line 1.")
        return

    end = text.find("\n---", 4)
    if end == -1:
        errors.append("The YAML frontmatter is not closed with ---. ")
        return

    block = text[4:end]

    name_match = re.search(r"^name:\s*(.+)$", block, re.MULTILINE)
    if not name_match:
        errors.append("The frontmatter is missing the name field.")
    else:
        value = name_match.group(1).strip()
        if not re.fullmatch(r"[a-z0-9-]{1,64}", value):
            errors.append(
                f"The name '{value}' is invalid. Use lowercase letters, numbers, "
                "and hyphens only, with a maximum of 64 characters."
            )
        if not value.endswith("-voice"):
            warnings.append(
                f"The name '{value}' does not end in -voice, which breaks the "
                "voice-cloner convention."
            )

    description_match = re.search(
        r"^description:\s*(.+)$", block, re.MULTILINE | re.DOTALL
    )
    if not description_match:
        errors.append("The frontmatter is missing the description field.")
    else:
        value = description_match.group(1).strip()
        if len(value) > 1024:
            errors.append(
                f"The description has {len(value)} characters; the limit is 1,024."
            )
        if len(value) < 80:
            warnings.append(
                "The description has fewer than 80 characters and may not contain "
                "enough triggers for the skill to be discovered."
            )


def validate_sections(text, errors):
    for section in REQUIRED_SECTIONS:
        if not re.search(
            rf"^##\s+.*{re.escape(section)}", text, re.MULTILINE | re.IGNORECASE
        ):
            errors.append(f"The required section '{section}' is missing.")


def validate_examples(text, errors, warnings):
    pairs = len(re.findall(r"^###\s+Example", text, re.MULTILINE | re.IGNORECASE))
    if pairs < 3:
        errors.append(
            f"Found {pairs} calibrated examples; at least 3 are required because "
            "examples teach voice more effectively than abstract rules."
        )
    elif pairs < 5:
        warnings.append(
            f"Found {pairs} calibrated examples. Five are recommended to cover "
            "different registers."
        )


def _line_is_prescriptive(line):
    """Ignore anti-patterns quoted as bad examples or explicitly prohibited."""
    lowered = line.strip().lower()
    if lowered.startswith(">"):
        return True
    triggers = [
        "avoid",
        "never use",
        "do not use",
        "don't use",
        "prohibit",
        "anti-pattern",
    ]
    return any(trigger in lowered for trigger in triggers)


def validate_anti_patterns(text, warnings):
    for number, line in enumerate(text.splitlines(), start=1):
        if _line_is_prescriptive(line):
            continue
        lowered = line.lower()
        for phrase in ANTI_PATTERNS:
            if phrase in lowered:
                warnings.append(
                    f"Line {number}: the anti-pattern '{phrase}' appears in the "
                    "document. Remove it unless the samples support it."
                )


def validate_placeholders(text, errors):
    for placeholder in PLACEHOLDERS:
        if placeholder in text:
            errors.append(
                f"The template placeholder '{placeholder}' remains in the final "
                "file and must be replaced."
            )


def main():
    if len(sys.argv) != 2:
        print("Usage: python3 scripts/validate_skill.py path/to/SKILL.md")
        sys.exit(2)

    path = sys.argv[1]
    try:
        text = read_file(path)
    except OSError as error:
        print(f"Could not read the file: {error}")
        sys.exit(2)

    errors, warnings = [], []

    validate_frontmatter(text, errors, warnings)
    validate_sections(text, errors)
    validate_examples(text, errors, warnings)
    validate_anti_patterns(text, warnings)
    validate_placeholders(text, errors)

    print(f"Validating {path}\n")

    if errors:
        print(f"ERRORS ({len(errors)}): the file is not ready for use:")
        for error in errors:
            print(f"  [x] {error}")
        print()

    if warnings:
        print(f"WARNINGS ({len(warnings)}): review before publishing:")
        for warning in warnings:
            print(f"  [!] {warning}")
        print()

    if not errors and not warnings:
        print("No errors or warnings. The structure is valid.")
        print("A valid structure does not prove that the voice was captured.")
        print("The meaningful test is a blind comparison with the voice owner.")
    elif not errors:
        print("No structural errors. Address warnings when they are relevant.")

    sys.exit(1 if errors else 0)


if __name__ == "__main__":
    main()
